@startuml

artifact masterdeploysubrg.ps1
artifact uploadParametersToBlob
artifact masterdeploysubrg.json
artifact masterdeployrg.json
artifact configureCiscoASAv
masterdeploysubrg.ps1 --> uploadParametersToBlob
uploadParametersToBlob --> masterdeploysubrg.json
masterdeploysubrg.json --> configureCiscoASAv
configureCiscoASAv --> masterdeployrg.json
uploadParametersToBlob --> masterdeployrg.json

@enduml