@startuml

artifact resourcegroups
artifact keyvaultinfra
artifact routescore
artifact routesmgmt
artifact routesshared
artifact nsgshared
artifact vnetsubnetcore
artifact vnetsubnetmgmt
artifact vnetsubnetshared
artifact vnetpeeringcore
artifact vnetpeeringmgmt
artifact vnetpeeringshared
artifact storagevmdiagMGMTRDS
artifact storagevmdiagSharedSandbox
artifact coreciscoasav
artifact jumpbox01MGMTRDS
artifact dockerdemoSharedSandbox

resourcegroups --> keyvaultinfra
resourcegroups --> routescore
resourcegroups --> routesmgmt
resourcegroups --> routesshared
resourcegroups --> nsgshared
resourcegroups --> storagevmdiagMGMTRDS
resourcegroups --> storagevmdiagSharedSandbox
routescore --> vnetsubnetcore
routesmgmt --> vnetsubnetmgmt
routesshared --> vnetsubnetshared
nsgshared --> vnetsubnetshared
vnetsubnetcore --> coreciscoasav
vnetpeeringcore --> dockerdemoSharedSandbox
vnetpeeringcore --> vnetpeeringmgmt
vnetpeeringcore --> vnetpeeringshared
vnetsubnetcore --> vnetpeeringcore
vnetsubnetmgmt --> vnetpeeringcore
vnetsubnetshared --> vnetpeeringcore
storagevmdiagMGMTRDS --> jumpbox01MGMTRDS
coreciscoasav --> jumpbox01MGMTRDS
storagevmdiagSharedSandbox --> dockerdemoSharedSandbox
coreciscoasav --> dockerdemoSharedSandbox
keyvaultinfra --> jumpbox01MGMTRDS
keyvaultinfra --> dockerdemoSharedSandbox

@enduml