@startuml

artifact routes_core
artifact routes_mgmt_ad
artifact routes_mgmt_mgmttocore
artifact routes_mgmt_rds
artifact routes_mgmt_test
artifact routes_shared_ad
artifact routes_shared_crm
artifact routes_shared_rds
artifact routes_shared_sandbox
artifact routes_shared_sharedtocore
artifact vnet_subnet_core
artifact vnet_subnet_mgmt
artifact vnet_subnet_shared
artifact vnet_peering_core
artifact vnet_peering_mgmt
artifact vnet_peering_shared
artifact core_cisco_asav
artifact mgmt_cisco_asav
artifact shared_cisco_asav

vnet_subnet_core --> routes_core
vnet_subnet_mgmt --> routes_mgmt_ad
vnet_subnet_mgmt --> routes_mgmt_mgmttocore
vnet_subnet_mgmt --> routes_mgmt_rds
vnet_subnet_mgmt --> routes_mgmt_test
vnet_subnet_shared --> routes_shared_ad
vnet_subnet_shared --> routes_shared_crm
vnet_subnet_shared --> routes_shared_rds
vnet_subnet_shared --> routes_shared_sandbox
vnet_subnet_shared --> routes_shared_sharedtocore
vnet_peering_core --> vnet_subnet_core
vnet_peering_core --> vnet_subnet_mgmt
vnet_peering_core --> vnet_subnet_shared
vnet_peering_mgmt --> vnet_peering_core
vnet_peering_shared --> vnet_peering_core
core_cisco_asav --> vnet_subnet_core
mgmt_cisco_asav --> vnet_peering_mgmt
shared_cisco_asav --> vnet_peering_shared

@enduml
