@startuml

artifact routes_core
artifact routes_mgmt
artifact routes_shared
artifact nsg_shared
artifact vnet_subnet_core
artifact vnet_subnet_mgmt
artifact vnet_subnet_shared
artifact vnet_peering_core
artifact vnet_peering_mgmt
artifact vnet_peering_shared
artifact core_cisco

vnet_subnet_core --> routes_core
vnet_subnet_mgmt --> routes_mgmt
vnet_subnet_shared --> routes_shared
vnet_subnet_shared --> nsg_shared
vnet_peering_core --> vnet_subnet_core
vnet_peering_core --> vnet_subnet_mgmt
vnet_peering_core --> vnet_subnet_shared
vnet_peering_mgmt --> vnet_peering_core
vnet_peering_shared --> vnet_peering_core
core_cisco --> vnet_subnet_core

@enduml
